---
demographics:
  min_age: 18
  max_age: 65
  required_properties:
  - played by
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  nickname_field: nickname
  nickname_format: "%{name} (%{nickname})"
  disable_auto_shortcuts: false
  editable_properties:
  - full name
  - nickname
  - gender
  - hair
  - physique
  demographics:
  - full name
  - nickname
  - gender
  - hair
  - eyes
  - skin
  - height
  - physique
  - played by
  - birthdate
  groups:
    Kind:
      desc: Your character's species.
      wiki: ''
      values:
        Water Folk: You are at home at in the water.
        Land Folk: You are a basic human.
        Elfin: You are one of the Elven People.
        Stoutling: You are one of the dwarven people.
        Beast-Kin: You are one of the anthromorphic beasts.
    Colony:
      desc: Your character's birth colony.
      wiki: ''
      values:
        Silver Isle: "You hail from the Silver Islands."
        Emerald Isle: "You hail from the Emerald Islands."
        Black Isle: "You hail from the Black Islands."
        Broken Isle: "You hail from the Broken Islands."
        Tradesport: "You hail from Tradesport."
        Floating People: "You hail from the Floating People."
        Wild Folk: "You hail from the uncivilized islands."
  shortcuts:
    groups: group
    colonies: group colony
    kinds: group kind
    demographics: demographic
    birthday: birthdate
    actors: census played by
    actor: demographic/set played by=
    fullname: demographic/set full name=
    playedby: demographic/set played by=
  help_text:
    playedby: "%xcplayedby <actor>%xn - The actor/actress depicting your character."
    physique: "%xcphysique <build/body type>%xn - athletic, wiry, slim, pudgy, etc."
    gender: "%xcgender <male/female/other>%xn"
    hair: "%xchair <hair color>%xn"
    eyes: "%xceyes <eye color>%xn"
    skin: "%xcskin <complexion>%xn"
    birthdate: "%xcbirthdate <mm/dd/yyy>%xn or %xcage <years>%xn"
    nickname: "%xcnickname <nickname>%xn - Optionally enter a nickname."
    fullname: "%xcfullname <name>%xn - Your character's full name."
  census_fields:
  - field: name
    width: 28
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 20
    title: Kind
    value: Kind
  - field: group
    width: 20
    title: Colony
    value: Colony
  private_properties: []
