---
demographics:
  census_fields:
  - field: name
    width: 28
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 20
    title: Faction
    value: Faction
  - field: group
    width: 20
    title: Position
    value: Position
  demographics:
  - played by
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  - streetname
  disable_auto_shortcuts: false
  editable_properties:
  - full name
  - hair
  - physique
  - streetname
  - gender
  groups:
    Faction:
      desc: What faction are you part of.
      values:
        Rebel: We fight the good fight against the tyranny of the keepers.
        Loyalist: We live to serve. We fight to keep the status quo.
        Civilian: I just want to survive today.
    Archetype:
      desc: What role do you play?
      values:
        The Addict: "Moving from one fix to another, this isn't always about drugs, there is sex, food, music or some other high."
        The Adherent: "There are rules, then there are rules, and both have to be followed, some maybe a little less strict but others must be to the letter. Whether it is legal, societal, religious or something else."
        The Adjudicator: "An unified front is what the goal is here, you work behind the scenes to grease the right palms, speak the right words, pay the right bribes to make it all work."
        The Advisor: "You don't claim to know it all, in fact, you often state you don't. What you have though is the right skill for the job. You know how to look beyond something and give the truth, whether good or bad. You help keep everyone walking the fine line."
        The Analyst: "There is nothing out of your reach when it comes to information. You collate, categorize and hunt down the information solely for the purpose of having the information."
        The Artist: "Expression is life. It takes many forms depending on the current vibe. Everything is a form of art and you must excel, you must leave your mark."
        The Athlete: "Like the competitor you strive to be the best at whatever sport or function you are part of, whether sports, martial arts, or just a really active person."
        The Bravo: "Misunderstood as the bully, the ruffian, tough as nails. Yeah that's you. No one tells you what to do and no one crosses you without paying for it."
        The Capitalist: "There is always something to gain. You are the wolf of wallstreet, that smooth talker that knows all the right ears to speak to. You can get what is needed and you'll do it willingly, for the right price, and that's not always money."
        The Caregiver: "To nurture and protect, a motto owned and beloved by the caregiver. You need to be needed, almost an obsession. You are always there, ready to be that valued shoulder to cry on."
        The Caretaker: "The steady gardener, the lonely maintenance man, the nanny, If something is broken, needs watched or just clean up things, you are the person for the job, and you are happy about that."
        The Competitor: "You are the champion. There are winners, there are losers and then there is you. Everything is a competition. You live to compete in all things and thrive only in glory and success."
        The Coward: "The winner is always the one who lives. You watch, you don't run toward, danger. That's fine. You survive because when the going gets tough, you get gone."
        The Crusader: "Everyone has something that drives them, for you its "The Right Thing" whatever that may be. Conviction is your shield, sword and armor."
        The Dabbler: "Jack of all trades and master of none, you know a little about everything and a lot about a bunch of stuff. You are the go-to-person when something has to be learned."
        The Defender: "You thrive only when protecting those who can't protect themselves. Whether you are a blind crusading lawyer or a friendly neighborhood good-doer, it is what drives you."
        The Deviant: "Life is a beat, everyone normally steps to the same one, but not you, rather your beat is off by varying degrees and that's just the way you like it. If someone is comfortable, you strive to make it awkward, faith is of no real importance, in the end."
        The Explorer: "Hello cat. Curiosity drives you like the itch you can't scratch. You must do everything, try everything and go everywhere. Bad stuff happens because of this, and because of that bad stuff you've learned a lot."
        The Fatalist: "Why bother, I'm just going to fail anyways. It doesn't matter that you have the skills to actually not fail, rather you just know some how you will fuck it up and never be able to recover. This is your life. #FML"
        The Fool: "There is a wisdom found only in insanity. You are the person that has gone there and come back. You know things are not quite right with the world, you speak about it openly, only to find scorn and mockery. You are a fool to believe in something, when nothing is there, or so it seems."
        The Gambler: "What is life without a little risk? The thrill of the chance of loss ravishes your body better than any lover ever could. Sometimes you win, and that's ok. Sometimes you lose, that's fine too. But to win or lose by the skin of your teeth, that's the sweet spot. That's what it is all about - The Risk."
        The Heretic: "There are two sides, and you're the side no one wants to hear. The Devil's Advocate, the ambulance chaser, the man who says, "Well she did dress like a whore and teased me." You are that person. When someone says something, you let them hear it how it really is, whether they like it or not. To be blunt, you're blunt, evilly so."
        The Idealist: "Much like the visionary, you think everything is great, but it could always be better. When someone says, "Just deal with it." You typically just reply with "Why?""
        The Innocent: "You didn't plan for this. You are over your head, barely treading water and the fact that you really have no clue what you are doing makes it even worse."
        The Loner: "Who needs friends when you can't stand people. The only safety in numbers is the one where you move faster than the slowest person. Friends, yeah no time for that shit. Keep up or die, stay or leave. You don't care."
        The Martyr: "Sacrifice is the ultimate deed of compassion. You lay it all on the line. If someone needs it, you give it. Your jacket during a snowstorm? Sure. If you die, at least they'll live. That's important right?"
        The Medic: "When bullets fly, you are as cold as ice. No matter what is going on around you, when someone needs fixing, you are johnny on the spot. No one gets left behind, no one dies on your watch. You are the MacGuyver of the EMT World."
        The Mystic: "New Age Witchcraft isn't just your thing, it's your life. You've found a way to make the Surge work for you, maybe you have the skill or maybe you don't, but you can make it happen every now and then and that's gone to your head."
        The Optimist: "This invasion will end, nevermind it's been 200 years. Nevermind that humanity has been thrown to the brink of extinction, It will end and all will be good. Everything is possible and as long as someone is standing, anything can happen. Right?"
        The Oracle: "Tormented by flashes of the past, present and future, you've seen something. You know what is going to happen, at least that is what everyone thinks. Whether by cards, bones or dice you have mastered the arts of the fortune teller."
        The Pedagogue: "Teaching and Learning, two essential things. You believe to stop learning means to die. To stop teach means to lose what humanity we have left. You know you don't know it all, but you'll share what you do with anyone who will listen."
        The Penitent: "It's all your fault. You left the light on one to many times. You burnt the pot roast the night of the invasion. Nevermind you couldn't have been alive. Everything is some how your fault. You know it. Even when someone says it isn't, you know better."
        The Perfectionist: "Perfection can be a blessing or a curse. Whatever you do, you have to do it perfectly or it bothers you."
        The Rebel: "The keepers have kept everyone down. You know the rules, and they are a trap. You strive to break free from the chains and walk your own path. No matter what, all you have is your own integrity."
        The Rogue: "When told do not do, you do. There are people who are born to just simply do whatever they know they shouldn't. Adventure only starts after that first sweet moment of rebellion. It's not the act of rebelling that feeds you, it is the adventure that comes afterward. Push the button. I dare you."
        The Scholar: ''
        The Stoic: ''
        The Survivor: ''
        The Thrill-Seeker: ''
        The Vigilante: ''
        The Visionary: ''
        The Judge: "When things go wrong, it often falls to you to make it right, whether you like it or not."
    Camp:
      desc: Which camp are you from?
      values:
        Eastland: 'You are from the Eastland Camp.'
        Westland: ''
        Midland: ''
        Downtown: ''
        Underground: ''
  help_text:
    actor: "%xcactor <actor>%xn - See 'help actors'."
    physique: "%xcphysique <build/body type>%xn - athletic, wiry, slim, pudgy, etc."
    gender: "%xcgender <male/female/other>%xn"
    hair: "%xchair <hair color>%xn"
    eyes: "%xceyes <eye color>%xn"
    skin: "%xcskin <complexion>%xn"
    birthdate: "%xcbirthdate <mm/dd/yyy>%xn or %xcage <years>%xn"
    streetname: "%xcstreetname <streetname>%xn - This is the name that most would
      know you by."
  max_age: 65
  min_age: 18
  nickname_field: streetname
  nickname_format: "%{name} (%{nickname})"
  private_properties: []
  required_properties:
  - played by
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  shortcuts:
    groups: group
    factions: group faction
    camps: group camp
    archetypes: group archetype
    demographics: demographic
    birthday: birthdate
    actors: census played by
    actor: demographic/set played by=
    fullname: demographic/set full name=
