---
fs3combat:
  armor:
    # Generic Armor
    None:
      description: In case you need to take off armor
      defense: 0
      protection:
        Nowhere: 0
    # Boat Armor
    1 Mast Boat:
      description: "The timbers of a small boat."
      protection:
        Hull: 8
        Waterline: 8
        Mast: 8
        Rigging: 7
    2 Mast Boat:
      description: "The timbers of a small boat."
      protection:
        Hull: 8
        Waterline: 8
        ForMast: 8
        AftMast: 8
        Rigging: 7
    Medium Heavy Warship:
      description: "The timbers of a medium heavy warship, like a Brig of War."
      protection:
        Hull: 12
        Waterline: 12
        Gundeck: 12
        Bow: 12
        Stern: 12
        Mainmast: 12
        Formast: 11
        Rigging: 8
    Medium Warship:
      description: "The timbers of a medium warship, like a brigantine."
      protection:
        Hull: 10
        Waterline: 10
        Gundeck: 10
        Bow: 10
        Stern: 10
        Mainmast: 10
        Formast: 9
        Rigging: 7
    Small Warship:
      description: "The timbers of a small warship, like a naval cutter."
      protection:
        Hull: 10
        Waterline: 10
        Gundeck: 10
        Bow: 10
        Stern: 10
        Mainmast: 10
        Rigging: 8
    Small Merchant Ship:
      description: "The timbers of a small merchant ship, like a sloop."
      protection:
        Hull: 9
        Waterline: 9
        Gundeck: 9
        Bow: 9
        Stern: 9
        Mainmast: 9
        Rigging: 7
    Large Heavy Warship:
      description: "The Timbers of a heavy large warship."
      protection:
        Hull: 20
        Waterline: 20
        Gundeck: 20
        Bow: 20
        Stern: 20
        Mainmast: 20
        Formast: 18
        Aftmast: 18
        Rigging: 16
    Large Warship:
      description: "The timbers of a large warhsip."
      protection:
        Hull: 12
        Waterline: 12
        Gundeck: 12
        Bow: 12
        Stern: 12
        Mainmast: 12
        Formast: 11
        Aftmast: 11
        Rigging: 8
    # Human Armor
    Breast Plate:
      description: "A solid steel cuirass with leather coat and pants. You can't swim in this."
      protection:
        Neck: 6
        Chest: 6
        Abdomen: 6
        Left Arm: 4
        Right Arm: 4
        Right Leg: 4
        Left Leg: 4
        Left Foot: 4
        Right Foot: 4
        Groin: 4
      allowed_specials:
        - Heavy Helmet
    Thick Coat:
      description: "A thick stiff leather coat and gloves."
      protection:
        Chest: 5
        Abdomen: 5
        Left Arm: 5
        Right Arm: 5
        Right Hand: 4
        Left Hand: 4
      allowed_specials:
        - Leather Hat
    Corset:
      description: A corsetted dress with a whalebone or wooden insert.
      protection:
        Abdomen: 5
    Fencing Jacket:
      description: "A thick, padded jacket meant for practicing fencing."
      protection:
        Chest: 4
        Abdomen: 4
        Left Arm: 4
        Right Arm: 4
    Pitch Coat:
      description: "A jacket and pants stiffened with pitch."
      protection:
        Chest: 4
        Abdomen: 4
        Right Arm: 4
        Left Arm: 4
        Right Leg: 4
        Left Leg: 4
        Right Foot: 4
        Left Foot: 4
        Groin: 4
    Leathers:
      description: "A basic set of leather armor."
      protection:
        Chest: 5
        Abdomen: 5
        Left Arm: 5
        Right Arm: 5
        Left Leg: 5
        Right Leg: 5
        Groin: 5
        Right Foot: 5
        Left Leg: 5
        Right Hand: 4
        Left Hand: 4
    # Beast Armor
    Epic Hide:
      description: "The legendarily tough hide or scales of some animals."
      defense: 4
      protection:
        # Primary Protection: 8
        # Secondary Protection: 6
        Mantle: 8
        Head: 8
        Arm: 6
        Rear Right Leg: 6
        Rear Left Leg: 6
        Front Right Leg: 6
        Front Left Leg: 6
        Chest: 8
        Abdomen: 8
        Neck: 6
        Groin: 6
        Tail: 6
        Right Flank: 6
        Left Flank: 6
        Left Leg: 6
        Right Leg: 6
        Thorax: 8
        Right Wing: 6
        Left Wing: 6
        Dorsal Fin: 6
        Ventral Fin: 6
        Right Pectoral Fin: 6
        Left Pectoral Fin: 6
        Blow Hole: 6
        Operculum: 6
        Tail Fin: 6
      allowed_specials:
        - Armor Plating
    Heavy Hide:
      description: "The exceptionally tough hide or scales of some animals."
      defense: 2
      protection:
        # Primary Protection: 6
        # Secondary Protection: 4
        Mantle: 6
        Head: 6
        Arm: 4
        Rear Right Leg: 4
        Rear Left Leg: 4
        Front Right Leg: 4
        Front Left Leg: 4
        Chest: 6
        Abdomen: 6
        Neck: 4
        Groin: 4
        Tail: 4
        Right Flank: 4
        Left Flank: 4
        Left Leg: 4
        Right Leg: 4
        Thorax: 6
        Right Wing: 4
        Left Wing: 4
        Dorsal Fin: 4
        Ventral Fin: 4
        Right Pectoral Fin: 4
        Left Pectoral Fin: 4
        Blow Hole: 4
        Operculum: 4
        Tail Fin: 4
      allowed_specials:
        - Armor Plating
    Light Hide:
      description: "The leathery hide of some animals."
      defense: 0
      protection:
        # Primary Protection: 4
        # Secondary Protection: 2
        Mantle: 4
        Arm: 2
        Head: 4
        Rear Right Leg: 2
        Rear Left Leg: 2
        Front Right Leg: 2
        Front Left Leg: 2
        Chest: 2
        Abdomen: 4
        Neck: 2
        Groin: 2
        Right Flank: 2
        Left Flank: 2
        Tail: 2
        Left Leg: 2
        Right Leg: 2
        Thorax: 4
        Right Wing: 2
        Left Wing: 2
        Dorsal Fin: 2
        Ventral Fin: 2
        Right Pectoral Fin: 2
        Left Pectoral Fin: 2
        Blow Hole: 2
        Operculum: 2
        Tail Fin: 2
      allowed_specials:
        - Armor Plating
    Medium Hide:
      description: "The tough hide or scales of some animals."
      defense: 1
      protection:
        # Primary Protection: 5
        # Secondary Protection: 3
        Mantle: 5
        Head: 5
        Arm: 3
        Rear Right Leg: 3
        Rear Left Leg: 3
        Front Right Leg: 3
        Front Left Leg: 3
        Chest: 5
        Abdomen: 5
        Neck: 3
        Groin: 3
        Right Flank: 3
        Left Flank: 3
        Tail: 3
        Left Leg: 3
        Right Leg: 3
        Thorax: 5
        Right Wing: 3
        Left Wing: 3
        Dorsal Fin: 3
        Ventral Fin: 3
        Right Pectoral Fin: 3
        Left Pectoral Fin: 3
        Blow Hole: 3
        Operculum: 3
        Tail Fin: 3
      allowed_specials:
        - Armor Plating
  armor specials:
    Heavy Helmet:
      description: A heavy helmet.
      protection:
        Head: 6
    Leather Hat:
      description: A tough leather hat.
      protection:
        Head: 3
    Armor Plating:
      description: "The creature has toughed armored plating."
      defense: 2
