---
fs3combat:
  weapons:
################################################################################
# Hoodoo Weapons
################################################################################
    Warding:
      description: "An barrier to defend against physical melee attacks and provide some minor offensive."
      skill: Hoodoo
      lethality: -10
      penetration: 0
      weapon_type: Melee
      is_automatic: false
      recoil: 1
      damage_type: physical
      accuracy: 0
      init_mod: -2
      has_shrapnel: false
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
    Bolt:
      description: "A blast of magical energy."
      skill: Hoodoo
      lethality: 5
      penetration: 0
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      has_shrapnel: false
      init_mod: 0
      accuracy: 0
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
    Blast:
      description: "An explosive blast of magical energy."
      skill: Hoodoo
      lethality: 10
      penetration: 0
      weapon_type: Explosive
      is_automatic: false
      recoil: 1
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: -2
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
    Burst:
      description: "A series of consecutive quick bolts of magical energy."
      skill: Hoodoo
      lethality: 0
      penetration: 0
      weapon_type: Ranged
      is_automatic: true
      recoil: 0
      damage_type: Physical
      init_mod: 0
      has_shrapnel: false
      accuracy: 0
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
  weapon specials:
    Fire:
      description: "Using the element of fire."
      lethality: 50
      penetration: 2
    Water:
      description: "Using the element of Water."
      lethality: 10
      damage_type: Stun
    Stone:
      description: "Using the hardened element of earth."
      lethality: 30
      penetration: 4
    Lightning:
      description: "Using the element of Lightning."
      lethality: 70
      penetration: 4
      damage_type: Stun
    Hellfire:
      description: "Using the element of fire infused with raw magic."
      penetration: 2
      lethality: 80
    Wind:
      description: "Using the element of wind."
      penetration: 0
      lethality: 15
