---
fs3combat:
  vehicles:
    Brig of War:
      description: "A brig-rigged ship designed for combat. 115-150 Crew, 12 guns per broadside."
      pilot_skill: Sailing
      toughness: 3
      hitloc_chart: 2 Mast Warship
      armor: Medium Heavy Warship
      weapons: Culverin
      dodge: -3
    Brigantine:
      description: "A merchant style ship with two masts. 40-100 Crew, 8 guns per broadside."
      pilot_skill: Sailing
      toughness: 1
      hitloc_chart: 2 Mast Warship
      armor: Medium Warship
      weapons: Culverin
      dodge: -4
    Cutter:
      description: "A small warship with a single mast. 70-100 crew, 8 guns per broadside."
      pilot_skill: Sailing
      toughness: 2
      hitloc_chart: 1 Mast Warship
      armor: Small Warship
      weapons: Culverin
      dodge: -2
    Lugger:
      description: "A fishing vessel with two masts. 10-30 Crew, 2 guns total, if any."
      pilot_skill: Sailing
      toughness: -1
      hitloc_chart: 2 Mast Ship
      armor: 2 Mast Boat
      weapons: Culverin
      dodge: -1
    Pinnance:
      description: "A ship's boat attached to another ship. 20 Crew, 1 gun if any."
      pilot_skill: Sailing
      toughness: -1
      hitloc_chart: 1 Mast Boat
      armor: 1 Mast boat
      weapons: Culverin
      dodge: 0
    Sloop:
      description: "A merchant ship with a single mast. 20-75 Crew, 4 guns per broadside."
      pilot_skill: Sailing
      toughness: 1
      hitloc_chart: Small Warship
      weapons: Culverin
      dodge: -2
      armor: Small Merchant Ship
    Clipper:
      description: "A large ship built for combat with 3 masts. 200-300 Crew, 20 guns per broadside."
      toughness: 4
      weapons: Culverin
      dodge: -3
      armor: Large Warship
      hitloc_chart: 3 Mast Boat
    Galleon:
      description: "A large heavy ship built for all out combat. 200-300 Crew, 25 guns per broadside."
      toughness: 5
      weapons: Culverin
      dodge: -3
      armor: Large Heavy Warship
      hitloc_chart: 3 Mast Boat
