---
fs3combat:
  treat_skill: Healing
  healing_skill: Healing
  recovery_skill: Brawn
  initiative_skill: Alertness
  composure_skill: Composure
  default_defense_skill: Reflexes
  strength_skill: Brawn
