---
fs3combat:
  weapons:
    # Required Weapons
    Shrapnel:
      description: Random Shrapnel
      skill: 3
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    # Faith Weapons
    Smite:
      description: "A prayer or invocation for damaging a target."
      skill: Faith
      lethality: 30
      penetration: 2
      weapon_type: Ranged
      is_automatic: false
      recoil: -3
      damage_type: physical
      has_shrapnel: false
      init_mod: -1
      accuracy: 3
      ammo: 3
      allowed_specials:
        - Greater Smite
    Rebuke:
      description: "A powerful wave of divine power to stun and possibly damage those before you."
      skill: Faith
      ammo: 1
      lethality: 50
      penetration: 4
      weapon_type: Explosive
      is_automatic: false
      recoil: -3
      damage_type: stun
      has_shrapnel: true
      init_mod: 0
      accuracy: 3
      allowed_specials:
        - Turn
    # Hoodoo Weapons
    Warding:
      description: "An barrier to defend against physical melee attacks and provide some minor offensive."
      skill: Hoodoo
      lethality: -10
      penetration: 0
      weapon_type: Melee
      is_automatic: false
      recoil: 1
      damage_type: physical
      accuracy: 0
      init_mod: -2
      has_shrapnel: false
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
    Bolt:
      description: "A blast of magical energy."
      skill: Hoodoo
      lethality: 5
      penetration: 0
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      has_shrapnel: false
      init_mod: 0
      accuracy: 0
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
    Blast:
      description: "An explosive blast of magical energy."
      skill: Hoodoo
      lethality: 10
      penetration: 0
      weapon_type: Explosive
      is_automatic: false
      recoil: 1
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: -2
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
    Burst:
      description: "A series of consecutive quick bolts of magical energy."
      skill: Hoodoo
      lethality: 0
      penetration: 0
      weapon_type: Ranged
      is_automatic: true
      recoil: 0
      damage_type: Physical
      init_mod: 0
      has_shrapnel: false
      accuracy: 0
      allowed_specials:
        - Fire
        - Water
        - Stone
        - Lightning
        - Hellfire
        - Wind
    # Bludgeoning Weapons
    Boarding Axe:
      description: "An axe made to climb up the side of a ship and fight onboard."
      skill: Bludgeons
      lethality: 10
      penetration: 6
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: physical
      accuracy: -1
      init_mod: -3
      has_shrapnel: false
      allowed_specials:
        - Sparring
    Club:
      description: "A belaying pin, club or a mace."
      skill: Bludgeons
      lethality: -5
      penetration: 5
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      has_shrapnel: false
      allowed_specials:
        - Sparring
        - Spiked
    Hatchet:
      description: "A small axe used more as a tool, than weapon."
      skill: Bludgeons
      lethality: 0
      penetration: 4
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: physical
      init_mod: 1
      accuracy: 0
      allowed_specials:
        - Sparring
    Great Hammer:
      description: "Not a tool, but a glorified smacker."
      lethality: 35
      skill: Bludgeons
      accuracy: 0
      init_mod: -3
      recoil: 0
      damage_type: Physical
      penetration: 7
      is_automatic: false
      has_shrapnel: false
      allowed_specials:
        - Sparring
        - Spiked
    # Firearms Weapons
    Brace of Pistols:
      description: "A pair of flintlock pistols."
      skill: Firearms
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      is_automatic: false
      ammo: 2
      recoil: 0
      damage_type: Physical
      init_mod: 1
      accuracy: 0
      has_shrapnel: false
  weapon specials:
    # Faith Weapon Specials
    Greater Smite:
      description: "A plea for greater help than normal."
      lethality: 15
      damage_type: Explosive
      has_shrapnel: true
      penetration: 4
    Turn:
      description: "Imbuing all your faith."
      lethality: 30
      damage_type: Physical
    # Hoodoo Weapon specials
    Fire:
      description: "Using the element of fire."
      lethality: 50
      penetration: 2
    Water:
      description: "Using the element of Water."
      lethality: 10
      damage_type: Stun
    Stone:
      description: "Using the hardened element of earth."
      lethality: 30
      penetration: 4
    Lightning:
      description: "Using the element of Lightning."
      lethality: 70
      penetration: 4
      damage_type: Stun
    Hellfire:
      description: "Using the element of fire infused with raw magic."
      penetration: 2
      lethality: 80
    Wind:
      description: "Using the element of wind."
      penetration: 0
      lethality: 15
