---
fs3combat:
  hitloc:
    Humanoid:
      areas:
        Chest:
        - Left Leg
        - Right Leg
        - Left Arm
        - Right Arm
        - Abdomen
        - Abdomen
        - Head
        - Chest
        - Chest
        - Chest
        Left Leg:
        - Chest
        - Right Foot
        - Right Leg
        - Right Leg
        - Abdomen
        - Abdomen
        - Left Foot
        - Left Leg
        - Left Leg
        - Left Leg
        Right Leg:
        - Chest
        - Left Foot
        - Left Leg
        - Left Leg
        - Abdomen
        - Abdomen
        - Right Foot
        - Right Leg
        - Right Leg
        - Right Leg
        Groin:
        - Abdomen
        - Abdomen
        - Abdomen
        - Left Leg
        - Right Leg
        - Left Leg
        - Right Leg
        - Groin
        - Groin
        - Groin
        Left Hand:
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Left Arm
        - Left Arm
        - Left Arm
        - Left Hand
        - Left Hand
        - Left Hand
        Right Hand:
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Right Arm
        - Right Arm
        - Right Arm
        - Right Hand
        - Right Hand
        - Right Hand
        Left Arm:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Left Hand
        - Left Hand
        - Left Arm
        - Left Arm
        - Left Arm
        Right Arm:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Right Hand
        - Right Hand
        - Right Arm
        - Right Arm
        - Right Arm
        Head:
        - Right Arm
        - Right Arm
        - Left Arm
        - Chest
        - Chest
        - Neck
        - Neck
        - Head
        - Head
        - Head
        Neck:
        - Right Arm
        - Right Arm
        - Left Arm
        - Chest
        - Chest
        - Head
        - Head
        - Neck
        - Neck
        - Neck
        Abdomen:
        - Left Leg
        - Right Leg
        - Left Leg
        - Right Leg
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
      vital_areas:
      - Chest
      - Abdomen
      critical_areas:
      - Head
      - Neck
      - Groin
