---
fs3skills:
  allow_unskilled_action_skills: true
  free_backgrounds: 6
  free_languages: 3
  max_ap: 40
  max_attr_rating: 4
  max_attrs_at_or_above:
    3: 4
    4: 2
  max_points_on_action: 28
  max_points_on_attrs: 12
  max_skill_rating: 7
  max_skills_at_or_above:
    5: 3
    6: 2
    7: 1
  min_backgrounds: 2
  starting_skills:
    Everyone:
      skills:
        Faith: 0
        Hoodoo: 0
        Spirit: 1
    Archetype:
      Priest:
        skills:
          Spirit: 2
          Faith: 2
          Composure: 2
      Witch:
        skills:
          Spirit: 2
          Hoodoo: 2
          Composure: 2
      Sailor:
        skills:
          Sailing: 2
          Athletics: 2
      Swashbuckler:
        skills:
          Blades: 2
          Sailing: 2
          Athletics: 2
      Shaman:
        skills:
          Spirit: 2
          Hoodoo: 1
          Faith: 1
          Composure: 2
      Trader:
        skills:
          Book Keeping: 2
          Composure: 2
          Haggling: 3
    Kind:
      Water Folk:
        skills:
          Water Breathing: 3
          Swimming: 3
          Reflexes: 3
          Athletics: 3
          Sailing: 2
      Elfin:
        skills:
          Quenya: 3
          Reflexes: 3
          Presence: 3
          Literacy: 3
          Blades: 2
      Stoutling:
        skills:
          Khuzdul: 3
          Brawn: 3
          Bludgeons: 2
          Reflexes: 1
      Beast-Kin:
        skills:
          Sylvan: 3
          Reflexes: 3
          Brawling: 2
          Athletics: 3
    Colony:
      Silver Isle:
        skills:
          Silvish: 3
      Black Isle:
        skills:
          Volkash: 3
      Emerald Isle:
        skills:
          Esmeth: 3
      Broken Isle:
        skills:
          Ettin: 3
      Floating People:
        skills:
          Seaspeak: 3
      Wild People:
        skills:
          Wildspeak: 3
  unusual_skills:
  - Wildspeak
  - Silvish
  - Esmeth
  - Ettin
  - Volkash
  - Hoodoo
  - Faith
  - Quenya
  - Khuzdul
  - Sylvan
  - Handspeak
  - Spiritspeak
  - Oldspeak
  advantages_cost: 2
