---
fs3skills:
  advantages:
  - name: Resources
    desc: Wealth and other tangible possessions.
  - name: Iron Will
    desc: A strong sense of self and willpower.
  - name: Clarity
    desc: Able to hold on to sanity in the face of horrors.
  advantages_blurb: 'Advantages represent important things your character possesses
    that are not skills.  Advantages are rated from 1-3. See [FS3: Advantages](http://aresmush.com/fs3/fs3-3/chargen/#advantages)
    for details.'
  use_advantages: true
