---
fs3skills:
  advantages:
  - name: Resources
    desc: Tangible possessions that have actual practical uses in the world today.
  - name: Treasures
    desc: Tangible possessions that are left over before the days of the invasion. They often only hold emotional value.
  advantages_blurb: 'Advantages represent important things your character possesses
    that are not skills.  Advantages are rated from 1-3. See [FS3: Advantages](http://aresmush.com/fs3/fs3-3/chargen/#advantages)
    for details.'
  use_advantages: true
