---
fs3skills:
  advantages:
  - name: Booty
    desc: Wealth and other tangible possessions.
  - name: Legend
    desc: How famous or infamous your name is.
  - name: Connections
    desc: How connected to the right people for the right job you are.
  advantages_blurb: 'Advantages represent important things your character possesses
    that are not skills.  Advantages are rated from 1-3. See [FS3: Advantages](https://aresmush.com/fs3/fs3-3/chargen.html#advantages)
    for details.'
  use_advantages: true
