---
fs3skills:
  max_luck: 50
  luck_for_scene:
    0: 0.1
    10: 0.075
    25: 0.05
    50: 0.025
  public_sheets: true
  roll_channel: FS3 Rolls
  shortcuts:
    spec: specialty
    sheet2: profile
    skills: abilities2
    attributes: abilities
    languages: abilities4
    bgskill: abilities3
    advantages: abilities5
    sorcery: abilities6
    practice: learn
    train: learn
    xp/raise: learn
