---
fs3skills:
  action_skills:
  - name: Alertness
    desc: Noticing things and being aware of your surroundings.
    linked_attr: Perception
  - name: Athletics
    desc: General running, jumping, climbing, etc.
    linked_attr: Brawn
  - name: Composure
    desc: Coolness under pressure.
    linked_attr: Grit
  - name: Blades
    desc: "Using knives, daggers, swords and other bladed weapons."
    linked_attr: Reflexes
  - name: Bludgeons
    desc: "Using axes, maces, and other heavy or weighted weapons."
    linked_attr: Brawn
  - name: Deception
    desc: "The ability to lie convincingly to NPCs. (Can be used to promote RP actions.)"
    linked_attr: Presence
  - name: Faith
    desc: "The ability to call upon higher powers to grant miracles."
    linked_attr: Spirit
  - name: Hoodoo
    desc: "The ability to summon mystic energy into spells."
    linked_attr: Spirit
    specialties:
      - Fire
      - Stone
      - Water
      - Lightning
      - Hellfire
      - Wind
  - name: Firearms
    desc: "Use pistols and muskets."
    linked_attr: Reflexes
  - name: Gunnery
    desc: "The ability to use mounted cannons and weaponry."
    linked_attr: Wits
  - name: Healing
    desc: "The ability to treat hurt and ill people."
    linked_attr: Wits
    specialties:
      - Traditional
      - Surgery
  - name: Persuasion
    desc: "The ability to convince an NPC to do what you want."
    linked_attr: Presence
  - name: Sailing
    desc: "Seamanship, knot tying, navigation and all other things to do with sailing."
    linked_attr: Wits
  - name: Stealth
    desc: "The ability to be sneaky and stealthy."
    linked_attr: Reflexes
  - name: Brawling
    desc: "The ability to fight with your hands and feet effectively."
    linked_attr: Brawn
  - name: Haggling
    desc: "The ability to haggle for the best deal."
    linked_attr: Wits
  action_skills_blurb: 'Action Skills represent your ability in areas deemed important
    for gameplay.  Action Skills are rated from 0-8, but some games limit the highest and lowest ratings. See [FS3: Action Skills](https://aresmush.com/fs3/fs3-3/chargen.html#action-skills)
    for details.'
