---
fs3skills:
  advantages:
  - name: Resources
    desc: Tangible possessions that have actual practical uses in the world today.
  - name: Treasures
    desc: Tangilbe possessions that are left over before the days of the invasion. They often only hold emotional value.
  - name: Augmented Sight
    desc: The Keepers augmented you enhanced vision. Gain a bonus equal to the rank of this to all visual perception based checks, add +1 to all ranged attacks.
  - name: Familiar CVI
    desc: You possess a Cyber Viral Implant familiar that helps control your surge. Gain a bonus equal to the rank of this for all Surge checks. Gain a +1 to all knowledge based checks.
  - name: In the Know
    desc: You have a secret piece of knowledge about the Keepers that will come in handy at just the right time. 
  advantages_blurb: 'Advantages represent important things your character possesses
    that are not skills.  Advantages are rated from 1-3. See [FS3: Advantages](http://aresmush.com/fs3/fs3-3/chargen/#advantages)
    for details.'
  use_advantages: true
