---
fs3skills:
  allow_unskilled_action_skills: true
  free_backgrounds: 6
  free_languages: 3
  max_ap: 40
  max_attr_rating: 4
  max_attrs_at_or_above:
    3: 4
    4: 2
  max_points_on_action: 28
  max_points_on_attrs: 12
  max_skill_rating: 7
  max_skills_at_or_above:
    5: 3
    6: 2
    7: 1
  min_backgrounds: 2
  starting_skills:
    Everyone:
      skills:
        Faith: 0
        Hoodoo: 0
        Spirit: 1
    Kind:
      Beast-Kin:
        skills:
          Sylvan: 3
  unusual_skills:
  - Wildspeak
  - Silvish
  - Esmeth
  - Ettin
  - Volkash
  - Hoodoo
  - Faith
  - Quenya
  - Khuzdul
  - Sylvan
  - Handspeak
  - Spiritspeak
  - Oldspeak
  advantages_cost: 2
  sorcery_cost: 10
