---
fs3skills:
  language_blurb: 'Languages represent your ability to speak and read other languages.  Languages
    have a descriptive rating.   See [FS3: Languages](https://aresmush.com/fs3/fs3-3/chargen.html#languages)
    for details.'
  starting_languages:
  - Tradespeak
  languages:
  - name: Tradespeak
    desc: The most common language on the planet. (English)
  - name: Silvish
    desc: The most common language of the Silver Isles.
  - name: Volkash
    desc: The most common language of the Black Isles.
  - name: Esmeth
    desc: The most common language of the Emerald Isles.
  - name: Seaspeak
    desc: The most common language of the Floating People.
  - name: Handspeak
    desc: A language derived from hand signs and motions. (ASL)
  - name: Spiritspeak
    desc: A language used to commune with the spirits. (Latin)
