---
fs3skills:
  action_dots_beyond_chargen_max: 17
  allow_advantages_xp: false
  attr_dots_beyond_chargen_max: 17
  days_between_learning: 30
  max_xp_hoard: 25
  periodic_xp: 2
  skills_requiring_training:
  - Demolitions
  - Gunnery
  - Medicine
  - Piloting
  - Occultism
  - Archery
  xp_costs:
    language:
      '0': 4
    action:
      '0': 1
      '1': 1
      '2': 2
      '3': 3
      '4': 6
      '5': 8
      '6': 8
      '7': 12
    background:
      '0': 1
      '1': 4
      '2': 8
    attribute:
      '1': 1
      '2': 4
      '3': 8
      '4': 16
    advantages:
      '0': 1
      '1': 4
      '2': 12
    magix:
      '0': 3
      '1': 4
      '2': 6
      '3': 8
      '4': 10
      '5': 15
      '6': 20
      '7': 25
  xp_cron:
    day_of_week:
    - Sat
    hour:
    - 3
    minute:
    - 30
