---
fs3skills:
  advantages_cost: 4
  allow_unskilled_action_skills: true
  free_backgrounds: 6
  free_languages: 2
  max_ap: 40
  max_attr_rating: 5
  max_attrs_at_or_above:
    '3': 7
    '4': 3
    '5': 1
  max_points_on_action: 28
  max_points_on_attrs: 12
  max_skill_rating: 8
  max_skills_at_or_above:
    '5': 3
    '6': 5
    '7': 2
    '8': 1
  min_backgrounds: 4
  starting_skills:
    Calling:
      Champion:
        attrs:
          Brawn: 3
          Reflexes: 3
        skills:
          Melee: 3
          Firearms: 3
          Athletics: 3
          Occultism: 0
      Grace:
        attrs:
          Perception: 3
          Grit: 3
        skills:
          Alertness: 4
          Composure: 5
          Occultism: 0
      Mender:
        attrs:
          Wits: 3
          Reflexes: 3
        skills:
          Medicine: 3
          Crafting: 3
          Demolitions: 3
          Occultism: 0
        specialties:
          Medicine:
          - First Aid
      Seeker:
        attrs:
          Reflexes: 4
        skills:
          Athletics: 3
          Stealth: 3
          Alertness: 3
          Occultism: 0
      Troubadour:
        attrs:
          Presence: 4
        skills:
          Crafting: 3
          Performance: 3
          Athletics: 3
          Occultism: 0
      Wiseman:
        attrs:
          Grit: 3
          Enlightenment: 2
        skills:
          Occultism: 3
          Alertness: 3
          Composure: 3
  unusual_skills:
  - Piloting
  - Gunnery
  - Demolitions
  - Occultism
  - Archery
  - Crafting
  - Performance
