---
skin:
  header: "%x!--------------------------------------------------------------------------------%xn"
  footer: "%x!--------------------------------------------------------------------------------%xn"
  divider: "%x!--------------------------------------------------------------------------------%xn"
  plain: "%x!--------------------------------------------------------------------------------%xn"
  line_with_text_color: "%x!"
  line_with_text_padding: "-"
  random_colors:
  - "%x63"
## #020203
## #4C6085
## #ACBEA3
## #3A7CA5
## #A05D4B
