---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: name
    width: 20
    title: Name
  - field: group
    value: colony
    width: 16
    title: Colony
  - field: group
    value: kind
    width: 18
    title: Kind
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
